"""Planner Agent — the first agent compiled from .octo format.

This file was generated by Compoctopus as a .octo spec, then annealed to Python.
It doesn't "know" how to write an agent — it follows the template exactly,
proving the compiler pattern works.

The planner creates execution plans from task descriptions. It decomposes
complex tasks into ordered steps with dependencies. This is the simplest
possible agent — it just plans, it doesn't execute.

Bootstrap position: Step 2 of the D:D→D sequence.
    Step 1: annealer.py (hand-written bootstrap kernel)
    Step 2: planner_agent.octo → planner_agent.py (THIS FILE)
    Step 3: specialist_agent.octo → specialist_agent.py (planner writes this)
    Step 4: specialist compiles all default arms from .octo specs
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


# =============================================================================
# Types — the planner's own type algebra
# =============================================================================

@dataclass
class PlanStep:
    """A single step in an execution plan."""
    name: str
    description: str
    depends_on: List[str] = field(default_factory=list)
    estimated_complexity: str = "medium"  # low, medium, high
    output_type: str = "artifact"  # artifact, decision, validation


@dataclass
class ExecutionPlan:
    """A complete plan for executing a task."""
    task_description: str
    steps: List[PlanStep] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def step_names(self) -> List[str]:
        return [s.name for s in self.steps]

    @property
    def is_valid(self) -> bool:
        """Check that all dependencies reference existing steps."""
        names = set(self.step_names)
        for step in self.steps:
            for dep in step.depends_on:
                if dep not in names:
                    return False
        return len(self.steps) > 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task_description,
            "steps": [
                {
                    "name": s.name,
                    "description": s.description,
                    "depends_on": s.depends_on,
                    "complexity": s.estimated_complexity,
                    "output": s.output_type,
                }
                for s in self.steps
            ],
            "metadata": self.metadata,
        }


# =============================================================================
# Planner — decomposes tasks into execution plans
# =============================================================================

class PlannerAgent:
    """Creates execution plans from task descriptions.

    This is the first Compoctopus-compiled agent. It follows the template
    exactly — no intelligence, just structure. The planner:

    1. Takes a task description
    2. Identifies the task type (build, analyze, test, deploy)
    3. Generates appropriate steps with dependencies
    4. Returns a validated ExecutionPlan

    It doesn't execute anything. It just plans.
    """

    # Task type → step templates
    TEMPLATES: Dict[str, List[PlanStep]] = {
        "build": [
            PlanStep(name="analyze", description="Analyze requirements and constraints",
                     estimated_complexity="low", output_type="decision"),
            PlanStep(name="design", description="Design the solution architecture",
                     depends_on=["analyze"], estimated_complexity="medium", output_type="artifact"),
            PlanStep(name="implement", description="Implement the solution",
                     depends_on=["design"], estimated_complexity="high", output_type="artifact"),
            PlanStep(name="test", description="Test the implementation",
                     depends_on=["implement"], estimated_complexity="medium", output_type="validation"),
        ],
        "analyze": [
            PlanStep(name="gather", description="Gather information and context",
                     estimated_complexity="low", output_type="artifact"),
            PlanStep(name="analyze", description="Analyze patterns and relationships",
                     depends_on=["gather"], estimated_complexity="medium", output_type="artifact"),
            PlanStep(name="report", description="Generate analysis report",
                     depends_on=["analyze"], estimated_complexity="low", output_type="artifact"),
        ],
        "test": [
            PlanStep(name="identify", description="Identify test targets and criteria",
                     estimated_complexity="low", output_type="decision"),
            PlanStep(name="write_tests", description="Write test cases",
                     depends_on=["identify"], estimated_complexity="medium", output_type="artifact"),
            PlanStep(name="execute", description="Execute test suite",
                     depends_on=["write_tests"], estimated_complexity="low", output_type="validation"),
            PlanStep(name="report", description="Report results and coverage",
                     depends_on=["execute"], estimated_complexity="low", output_type="artifact"),
        ],
        "deploy": [
            PlanStep(name="validate", description="Validate deployment prerequisites",
                     estimated_complexity="low", output_type="validation"),
            PlanStep(name="stage", description="Stage deployment artifacts",
                     depends_on=["validate"], estimated_complexity="medium", output_type="artifact"),
            PlanStep(name="deploy", description="Execute deployment",
                     depends_on=["stage"], estimated_complexity="medium", output_type="artifact"),
            PlanStep(name="verify", description="Post-deployment verification",
                     depends_on=["deploy"], estimated_complexity="low", output_type="validation"),
        ],
    }

    def plan(self, task_description: str, task_type: Optional[str] = None) -> ExecutionPlan:
        """Create an execution plan for a task.

        Args:
            task_description: What needs to be done.
            task_type: Override task type detection. If None, inferred.

        Returns:
            Validated ExecutionPlan.
        """
        if task_type is None:
            task_type = self._detect_task_type(task_description)
        
        template = self.TEMPLATES.get(task_type, self.TEMPLATES["build"])
        
        # Deep copy the template so we don't mutate shared state
        steps = [
            PlanStep(
                name=s.name,
                description=f"{s.description} for: {task_description[:60]}",
                depends_on=list(s.depends_on),
                estimated_complexity=s.estimated_complexity,
                output_type=s.output_type,
            )
            for s in template
        ]
        
        plan = ExecutionPlan(
            task_description=task_description,
            steps=steps,
            metadata={"task_type": task_type, "template_used": task_type},
        )
        
        if not plan.is_valid:
            raise ValueError(
                f"Generated plan is invalid for task '{task_description[:40]}'. "
                f"Steps: {plan.step_names}. Check dependency references."
            )
        
        return plan

    def _detect_task_type(self, description: str) -> str:
        """Detect task type from description keywords."""
        desc_lower = description.lower()
        keywords = {
            "build": ["build", "create", "implement", "make", "write", "add"],
            "analyze": ["analyze", "investigate", "research", "understand", "study"],
            "test": ["test", "verify", "check", "validate", "assert"],
            "deploy": ["deploy", "release", "ship", "publish", "launch"],
        }
        scores = {}
        for task_type, words in keywords.items():
            scores[task_type] = sum(1 for w in words if w in desc_lower)
        
        if not any(scores.values()):
            return "build"  # default
        
        return max(scores, key=scores.get)

    def __repr__(self) -> str:
        return "PlannerAgent(templates={})".format(list(self.TEMPLATES.keys()))
